# Actividades Capítulo 7.


# Tratamiento de datos, estadística descriptiva y visualización de datos

## Resumen de actividades

- **Unidad 34.** Uso de módulos de Python
- **Unidad 35.** Serie Pandas para el tratamiento de datos
- **Unidad 36.** Pandas DataFrame para procesamiento de datos
- **Unidad 37.** Ordenación de datos
- **Unidad 38.** Datos de series temporales

# Actividad: Importación de módulos y su uso.


## Instrucciones

1. Importe los módulos que te permitan trabajar con fechas y tiempo (modulo datetime).

2. Use los diferentes métodos relacinados a operaciones con fechas y hora.

3. En el siguiente apartado revisa cada una las fechas contenidas en la lista e imprima el número de semanas y los dias restantes para llegar a esa fecha.

In [ ]:
from datetime import datetime
from dateutil.parser import parse

lista_de_fechas = ["04/01/2024", "01-28-2024", "2024-03-16", "05/24/2024", "07/30/2025"]

fechaHoy = datetime.now()
anio = fechaHoy.year
mes = fechaHoy.month
dia = fechaHoy.day

formatoHoy = datetime.strptime(f"{dia}/{mes}/{anio}", '%d/%m/%Y')

for feha in lista_de_fechas:
  feha = parse(feha)
  fecha_formateada = datetime.strptime(f"{feha.day}/{feha.month}/{feha.year}", '%d/%m/%Y')
  diferencia = fecha_formateada - formatoHoy
  print("*-"*15)
  print(f"La diferencia en dias de {formatoHoy} hasta {fecha_formateada} es de : {diferencia.days} dias.")
  print(f"{diferencia.days} dias son {diferencia.days // 7}.{diferencia.days % 7} semanas.")
  print()


'''

from datetime import datetime

fecha1 = datetime.strptime("4/1/2024", '%d/%m/%Y')
fecha2 = datetime.strptime("1/2/2024", '%d/%m/%Y')

diferencia = fecha2 - fecha1

# Obtiene la diferencia en días
dias_diferencia = diferencia.days

print(f"Diferencia en días: {dias_diferencia}")

'''

# Actividad: Manejo de la biblioteca Pandas.


## Instrucciones


1. Crear una serie de pandas, donde su indice este compuesto por fechas y en columna principal almace los valoras cargados en una lista.

2. Graficar los valores de la lista en función de la fecha.

In [ ]:
# Espacio para desarrollar el código y agregar los comentarios necesarios.

import pandas as pd
precios = [140, 130, 120, 115, 160, 110, 170, 150, 157, 135]

serie = pd.Series(precios)
print(serie)

#El 2do punto no lo entendí, so...

#df = pd.DataFrame({f'columns=': precios})
#print(df)

# Actividad: Operaciones con Data Frames


## Instrucciones


1. Dado el siguiente diccionario construya un objeto DataFrame.
2. Filtre los resultados por año de publicación.
3. Obtenga algunas columnas basado en que contenga alguna palabra en el nombre de la publicacion.

In [ ]:

import pandas as pd

publicaciones_literarias = {
    1605: "Don Quijote de la Mancha - Miguel de Cervantes",
    1865: "Alicia en el país de las maravillas - Lewis Carroll",
    1949: "1984 - George Orwell",
    1954: "El Señor de los Anillos - J.R.R. Tolkien",
    1997: "Harry Potter y la piedra filosofal - J.K. Rowling",
    2003: "El Código Da Vinci - Dan Brown",
    2002: "Inventado para probar que el filtro funcione bien - Dan Brown"
}

data = list(publicaciones_literarias.items())

df = pd.DataFrame(data, columns=["Año", "Publicación - Autor"])

print("DataFrame original:")
print(df)
print()

print("Filtrado por año:")
df_filtrado_año = df[df["Año"] == 2002]
print(df_filtrado_año)
print()

print("Filtrado por palabra:")
df_filtrado_palabra = df[df["Publicación - Autor"].str.contains("Anillos")]
print(df_filtrado_palabra)

 Actividad: Operaciones con DataFrames.


## Instrucciones


1. Descargue el archivo ted.csv del siguiente link: https://www.kaggle.com/datasets/rounakbanik/ted-talks
 y guardelo en el mismo directorio donde está localizado el notebook.

2. Lea el archivo csv como un dataframe.

3. Muestre la cabecera o las primeras files del DataFrame.

4. Verifique el tipo de datos contenido en cada una las columnas.

5. Verifique el número de registros perdidos.

6. En una columna adicional calcule el número de comentarios entre el número de vistas.

In [162]:
# Espacio para desarrollar el código y agregar los comentarios necesarios.
import pandas as pd
#1,2,3
df = pd.read_csv(r'C:\Users\IngCa\OneDrive\Escritorio\Programacion\VS Code\Python\Samsung Innovation Campus - Course Python\ted_main.csv')

   comments                                        description  duration  \
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164
1       265  With the same humor and humanity he exuded in ...       977
2       124  New York Times columnist David Pogue takes aim...      1286
3       200  In an emotionally charged talk, MacArthur-winn...      1116
4       593  You've never seen data presented like this. Wi...      1190

     event   film_date  languages   main_speaker  \
0  TED2006  1140825600         60   Ken Robinson
1  TED2006  1140825600         43        Al Gore
2  TED2006  1140739200         26    David Pogue
3  TED2006  1140912000         35  Majora Carter
4  TED2006  1140566400         48   Hans Rosling

                                            name  num_speaker  published_date  \
0      Ken Robinson: Do schools kill creativity?            1      1151367060
1           Al Gore: Averting the climate crisis            1      1151367060
2                  David Pogue: Simplicity sells            1      1151367060
3             Majora Carter: Greening the ghetto            1      1151367060
4  Hans Rosling: The best stats you've ever seen            1      1151440680

                                             ratings  \
0  [{'id': 7, 'name': 'Funny', 'count': 19645}, {...
1  [{'id': 7, 'name': 'Funny', 'count': 544}, {'i...
2  [{'id': 7, 'name': 'Funny', 'count': 964}, {'i...
3  [{'id': 3, 'name': 'Courageous', 'count': 760}...
4  [{'id': 9, 'name': 'Ingenious', 'count': 3202}...

                                       related_talks  \
0  [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...
1  [{'id': 243, 'hero': 'https://pe.tedcdn.com/im...
2  [{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...
3  [{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...
4  [{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...

                     speaker_occupation  \
0                       Author/educator
1                      Climate advocate
2                  Technology columnist
3    Activist for environmental justice
4  Global health expert; data visionary

                                                tags  \
0  ['children', 'creativity', 'culture', 'dance',...
1  ['alternative energy', 'cars', 'climate change...
2  ['computers', 'entertainment', 'interface desi...
3  ['MacArthur grant', 'activism', 'business', 'c...
4  ['Africa', 'Asia', 'Google', 'demo', 'economic...

                             title  \
0      Do schools kill creativity?
1      Averting the climate crisis
2                 Simplicity sells
3              Greening the ghetto
4  The best stats you've ever seen

                                                 url     views  \
0  https://www.ted.com/talks/ken_robinson_says_sc...  47227110
1  https://www.ted.com/talks/al_gore_on_averting_...   3200520
2  https://www.ted.com/talks/david_pogue_says_sim...   1636292
3  https://www.ted.com/talks/majora_carter_s_tale...   1697550
4  https://www.ted.com/talks/hans_rosling_shows_t...  12005869

   comentarios_por_vista
0               0.000096
1               0.000083
2               0.000076
3               0.000118
4               0.000049

In [159]:
print(df.head())

   comments                                        description  duration  \
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164
1       265  With the same humor and humanity he exuded in ...       977
2       124  New York Times columnist David Pogue takes aim...      1286
3       200  In an emotionally charged talk, MacArthur-winn...      1116
4       593  You've never seen data presented like this. Wi...      1190

     event   film_date  languages   main_speaker  \
0  TED2006  1140825600         60   Ken Robinson
1  TED2006  1140825600         43        Al Gore
2  TED2006  1140739200         26    David Pogue
3  TED2006  1140912000         35  Majora Carter
4  TED2006  1140566400         48   Hans Rosling

                                            name  num_speaker  published_date  \
0      Ken Robinson: Do schools kill creativity?            1      1151367060
1           Al Gore: Averting the climate crisis            1      1151367060
2                  David Pogue: Simplicity sells            1      1151367060
3             Majora Carter: Greening the ghetto            1      1151367060
4  Hans Rosling: The best stats you've ever seen            1      1151440680

                                             ratings  \
0  [{'id': 7, 'name': 'Funny', 'count': 19645}, {...
1  [{'id': 7, 'name': 'Funny', 'count': 544}, {'i...
2  [{'id': 7, 'name': 'Funny', 'count': 964}, {'i...
3  [{'id': 3, 'name': 'Courageous', 'count': 760}...
4  [{'id': 9, 'name': 'Ingenious', 'count': 3202}...

                                       related_talks  \
0  [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...
1  [{'id': 243, 'hero': 'https://pe.tedcdn.com/im...
2  [{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...
3  [{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...
4  [{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...

                     speaker_occupation  \
0                       Author/educator
1                      Climate advocate
2                  Technology columnist
3    Activist for environmental justice
4  Global health expert; data visionary

                                                tags  \
0  ['children', 'creativity', 'culture', 'dance',...
1  ['alternative energy', 'cars', 'climate change...
2  ['computers', 'entertainment', 'interface desi...
3  ['MacArthur grant', 'activism', 'business', 'c...
4  ['Africa', 'Asia', 'Google', 'demo', 'economic...

                             title  \
0      Do schools kill creativity?
1      Averting the climate crisis
2                 Simplicity sells
3              Greening the ghetto
4  The best stats you've ever seen

                                                 url     views
0  https://www.ted.com/talks/ken_robinson_says_sc...  47227110
1  https://www.ted.com/talks/al_gore_on_averting_...   3200520
2  https://www.ted.com/talks/david_pogue_says_sim...   1636292
3  https://www.ted.com/talks/majora_carter_s_tale...   1697550
4  https://www.ted.com/talks/hans_rosling_shows_t...  12005869

In [158]:
print("Tipos de datos: ")
print(df.dtypes)

Tipos de datos:
comments               int64
description           object
duration               int64
event                 object
film_date              int64
languages              int64
main_speaker          object
name                  object
num_speaker            int64
published_date         int64
ratings               object
related_talks         object
speaker_occupation    object
tags                  object
title                 object
url                   object
views                  int64
dtype: object

In [165]:
df['comentarios_por_vista'] = df['comments'] / df['views']
print(df['comentarios_por_vista'])

0       0.000096
1       0.000083
2       0.000076
3       0.000118
4       0.000049
          ...
2545    0.000038
2546    0.000014
2547    0.000027
2548    0.000076
2549    0.000020
Name: comentarios_por_vista, Length: 2550, dtype: float64

In [161]:
print("Registros perdidos: ")
print(df.isna().sum())

Registros perdidos:
comments              0
description           0
duration              0
event                 0
film_date             0
languages             0
main_speaker          0
name                  0
num_speaker           0
published_date        0
ratings               0
related_talks         0
speaker_occupation    6
tags                  0
title                 0
url                   0
views                 0
dtype: int64